## Studis haben auch Rechte! Oder so ähnlich ... - Klausuren und andere Katastrophen

Ihr kennt es bestimmt noch alle aus der Schule: Wenn man eine Klausur geschrieben hat, bekommt man sie am Ende vom Lehrer benotet wieder zurück.
Danach konnte man dann mit den Lehrern mehr oder weniger erfolgreich über die Punktevergabe diskutieren und eventuell manchmal sogar noch die Note aufbessern.
In der Uni ist das nicht mehr so. Nachdem eure Klausuren korrigiert worden sind, werden die Ergebnisse in der Regel ausgehängt oder auch im Internet auf den Lehrstuhlseiten oder im eLearning veröffentlicht.
Ihr seht also erst einmal nur eure Matrikelnummer und eure Note. Um nun herauszufinden, ob ihr noch Punkte bekommen könnt,
um die Note eventuell zu verbessern, müsst ihr zur Einsicht der Klausur (i.d.R. beim betreffenden Dozenten) gehen. Es kann durchaus vorkommen,
dass sich beim Aufsummieren der Punkte verzählt wird oder Ähnliches, darum ist es sinnvoll diesen Termin wahrzunehmen. Jedoch gibt es hier ein Problem:

Viele Dozenten bieten keine Einsichten an. Das bedeutet für euch, dass die Klausur direkt ans Prüfungsamt weitergeleitet wird und ihr sie erst dort einsehen könnt.
Fallen euch dann Unklarheiten auf, müsst ihr (evtl. mit einem Foto der Klausur) zum Dozenten gehen und das Prüfungsamt muss eure Klausur an diesen schicken,
damit ihr dann gemeinsam noch einmal darüber diskutieren könnt. Dies kann durchaus einige Zeit dauern und ist ziemlich nervig.

Darum ist es gut, wenn ihr eure Dozenten höflich um eine Einsicht bittet, falls diese nicht direkt angeboten wird.
Außerdem solltet ihr euch im Klaren sein, dass ein Dozent seine Einsichten eventuell nicht mehr durchführt, wenn ihr unhöflich oder respektlos seid.
In der Vergangenheit kam es leider vor, dass Dozenten in den Evaluationsbögen beleidigt wurden oder nach der Einsicht Beschwerden eingingen, die im falschen Ton formuliert waren.
Man müsste meinen es wäre common-sense höflich und respektvoll zu sein, aber bedauerlicherweise ist dies nicht der Fall.

Ebenfalls wichtig sind die bereits erwähnten Evaluationen, die jedes Semester in einem Fachbereich unserer Fakultät durchgeführt werden.
Sie sind natürlich anonym und ihr könnt so helfen die Lehre an der Fakultät erheblich zu verbessern. Die Evaluationen werden in der Regel kurz nach der Semestermitte durchgeführt und ausgewertet.
Nach der Auswertung werden die Ergebnisse an die betreffenden Dozenten zurückgeschickt. Diese sollen dann eigentlich mit euch Rücksprache über die Ergebnisse halten.
Das tun sie nur leider meistens nicht. Also gilt auch hier: sprecht eure Dozenten darauf an. Fragt nach den Ergebnissen der Evaluation und versucht konstruktive Kritik zu geben.